site_name: Ojo Fotográfico


pages:
    - Inicio: index.md

    - Mi Blog:
      - Radal Siete Tazas: radal.md
      - Postales: postales.md
      - Chiflón del diablo: chiflon.md

#    - Root:
#      - Sub Menu Tazas: submenu.md
theme:
  name: 'material'
  font:
    text: 'Montserrat'
    code: 'Space Mono'
